[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[theme]
primaryColor = "#FF914D"
backgroundColor = "#F8F9FA"
secondaryBackgroundColor = "#E0E0E0"
textColor = "#262730"
font = "sans serif"
